[package]
name = "proxy_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
tokio = { version = "1.45.0", features = ["sync"] }
